### ISSUE TITLE
Elevation discontinuity

### ISSUE THREAD

**Issue by ninnghazad** [GeoscienceAustralia/anuga_core#170]
Hey there.
I am trying model a jump in elevation, a step as in stairs - but am having a hard time getting this to work.
From source and documentation i got to believe that this is something that can be done using ANUGA.
What i am looking for is to insert a breakline and have a sharp/vertical jump in the model at that location. For buildings and similar features.

Currently i try like this:
- Create triangular net mesh like usual, but with breaklines.
- Play with settings like unique_vertices and discontinuous_elevation
- Assign values to vertices from external data.
(At this point i have a nice and smooth model.)
- Iterate over breaklines to search corresponding nodes and triangles.
- Use set_quantity('elevation', location=vertices ...) to manipulate elevations.

When i write out the domain as sww at this point, i can see the model just like i want to it to be.
Smooth model with jumps at specified places.
But as soon as i start actual simulation, the triangles i manipulated seem to get overriden with their centroid values. So i get flat triangles, which do however have non-smooth transisitions to neighbours.

I think i am supposed to set:
set_store_vertices_smoothly(False)
set_store_vertices_uniquely(True)
set_using_discontinuous_elevation(True) # default for DE methinks
algo = DE*

I must be doing it wrong - can anybody shed some light on this to help me out?

**Comment by stoiver** [comment]
@ninnghazad you should be able to do what you want without too much trouble. You might like to look at a workshop/clinic that I just presented at the CSDMS workshop, https://github.com/stoiver/anuga-clinic-2018

You can fire up the python notebooks on the google cloud, colab. Anyway it provides a number of ways to produce discontinuous elevations. 

I would definitely suggest using the standard algorithm DE0 or DE1 which both use discontinuous elevation. I.e. the quantities elevation, stage, xmomentum and ymomentum are all centroid based quantities. 

The commands 

```
set_store_vertices_smoothly(False)
set_store_vertices_uniquely(True)
```

These just control how the output is written to the sww file. 

By the way 

`set_store_vertices_smoothly(False)` is equivalent to  `set_store_vertices_uniquely(True)`

They control how smoothly the vertex values of the quantities are stored to the sww file. THese are derived from the basic centroid values. We initially decided to store vertex values so that our anuga_viewer would make nice smooth visualisations.  The command 

```
set_store_vertices_smoothly(True)
```

produces a smooth visualisation, while 

```
set_store_vertices_smoothly(False)
```

saves the underlying discontinuous piecewise linear reconstruction of the conserved quantities. 

But the really basic quantities are the centroid values. The sww file now also stores the underlying centroid values of the conserved quantities, which you can interrogate using plot_utils (and also I wrote some simple code for the anuga_clinic to plot sww files within the colab python notebook). 

Hope the clinic notebooks help.

**Comment by ninnghazad** [comment]
@stoiver, thanks for the response.
I read the 3 notebooks, and also a paper written by (i assume) you and a colleague titled "Open source flood simulation with a 2D discontinuous-elevation hydrodynamic model". I think i have a better grasp now on what is meant by discontinuous-elevation within ANUGA. However, what i am not certain about how and if breaklines (as in the lines i supply to mesh generation under the name breaklines) produce rapid change in elevation compared to non-breakline-edges. 
consider two centroids (z0=1,z1=2) as part of two identically shaped triangles, sharing an edge. now as i understand ANUGA would allow that edge to have different z for the two triangles depending on the neighbours of each triangle. would both triangles be embedded in a plane with their respective z, i would imagine the gradient formed between both centroids to be sloped, but discontinuous at the edge. now how would that edge being set as a breakline (in the manner mentioned above) change that behaviour? would half-edge e0 now be at z=z0 and e1 at z=z1 ?
i kind of hope that is how it works - i got the impression from the last part of the paper and fig.3 (the one with a channel formed by breaklines). but i am unsure because i have used (the very awesome) triangle.c a bunch and it might be that breaklines are "just" for triangle.c to be used as constraint segments and that the actual rapid change in elevation i hope to achieve is defined using some other means.

aside, the notebooks are a nice read - i checked out usage of interior_holes, and while it's not what i need atm (i want the roofs to catch direct rain), i am sure i have uses for that too. maybe when doing flooding-by-river kind of simulations in the future. riverwalls - also a nice feature should i ever need a weir (trying to use these for my purposes produced rather strange results, which are probably expected now that i have read more about them).

**Comment by stoiver** [comment]
@ninnghazad, we just use the breaklines to create the mesh. But they are useful to produce river banks for instance. Then you have to setup your elevation to take advantage of the underlying mesh. For instance setup two breaklines to define the banks of a river. Then set the elevation quantity (at the centroids) to some given DEM. And then set some lower values within the river (by restricting the application to a polygon made up of the two breaklines combined appropriately). 

Also your application, use the breaklines to setup the extends of your buildings, apply a standard elevation over the whole domain, and then apply an updated elevation for each of your buildings (could add a constant amount to the current elevation, or set particular values. Have a look at the merewether case study in the validation tests, which has options to either cutout buildings or leave them in and change elevation. 

When calculating the stage, height and elevation at the midpoint of an edge, we create a  piecewise linear reconstruction of the stage and height using the centroid values of those quantities. We then set the value of the elevation at the edge points as elev_m = stage_m - height_m. So even if the centroid value of the elevation remains constant, the midpoint values of elevation will change. This somewhat counter intuitive  behaviour actually allows us to ensure that the scheme is well balanced, which is actually very important to ensure accurate representation of flows into lakes.
