### ISSUE TITLE
Problem in running

### ISSUE THREAD

**Issue by Mariob96** [GeoscienceAustralia/anuga_core#243]
I had problems in running ANUGA because there where missing parenthesis on "print" or "raise", and problems in "import"

for example:
Traceback (most recent call last):
  File "setup.py", line 169, in <module>
    setup_package()
  File "setup.py", line 126, in setup_package
    from anuga.utilities.system_tools import store_revision_info
  File "/home/mario/anuga_core/anuga/utilities/system_tools.py", line 27
    if verbose: print s

Can I ask you how can i fix this problem? I tried correcting this problems manually but seems to me a huge effort. 
Thank you in advance

**Comment by stoiver** [comment]
@Mariob96 the default version of anuga on GeoscienceAustralia is written in Python 2.7.  Hence the use of `print` instead of `print(  )`. 

There is a python 3 version which you can find in the anuga_py3 branch. This is the default version being developed at http://github.com/anuga-community/anuga_core
