### ISSUE TITLE
Installation issue: Anuga_parallel with Intel MPI

### ISSUE THREAD

**Issue by samcom12** [GeoscienceAustralia/anuga_core#248]
I tried installing Anuga in parallel with Intel MPI. In the documentation, we have used either openmpi or mpich2.
Running tests with Intel MPI fails with signal 9 always.
Any plan for supporting Intel MPI?

with command- 

**_export ANUGA_PARALLEL="openmpi"_**

Shall I use  **_export ANUGA_PARALLEL="intelmpi"_** ?

**Comment by stoiver** [comment]
@samcom12 there is a python 3.8 version of anuga. Available as branch anuga_py3. That uses mpi4py. So you should be able to get mpi4py to install using Intel and python 3.8

By the way, the environment variable ANUGA_PARALLEL is only used when testing anuga under travis CI. If you install mpi and then pypar (if using python 2 version of anuga) or mpi4py (for python 3 version of anuga) then you should be fine to run.

**Comment by samcom12** [comment]
@stoiver Thanks for your input. I have tried the  **anuga_py3** branch and I could run it properly. I think we need a proper installation document for the same.

**Comment by dark957** [comment]
hello  I want to know where can I download  anuga_py3

**Comment by dark957** [comment]
Dear Stephen Roberts:
&nbsp; &nbsp; &nbsp; I am a PhD student of&nbsp; Hohai university, Nanjing, China. When I tested "python runtests.py", there came the errors as figures showed. I wish you could guide me how to deal with it.
Sincerely.
Yao Du








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GeoscienceAustralia/anuga_core"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月12日(星期二) 下午3:14
***@***.***&gt;;
抄送:&nbsp;"BLACK ***@***.******@***.***&gt;;
主题:&nbsp;Re: [GeoscienceAustralia/anuga_core] Installation issue: Anuga_parallel with Intel MPI (#248)





 
@dark957 we have just setup the default main branch to be the python 3 version of anuga (and this needs mpi4py which should be available).
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
