### ISSUE TITLE
bring back domain.set_minimum_storable_height(minimum_storable_height) 

### ISSUE THREAD

**Issue by ghost** [GeoscienceAustralia/anuga_core#29]
In the past (when 1_5 solver was the default), we were able to tell ANUGA to filter out very shallow water depths on the domain. 

This was very useful when running rainfall on the domain models (for flood modelling work).

Now that DE0 solver is the default, this option is not available. 

Can you please add this feature back to ANUGA.

**Comment by stoiver** [comment]
Hi Petar, 

We should be able to look into this. In fact I'm surprised it doesn't work with DE_0. 

Do you have a simple example showing the problem, and how you test that it isn't working.

Thanks
steve

**Comment by gareth-d-ga** [comment]
Hi Petar,
Just checking -- are you making the call after any parallel distributes?
From memory, this parameter is set in the DE algorithms init routines, to ensure that full output was produced -- because historically I always wanted this for testing/debugging purposes. But I would have guessed that if you called the function after any parallel distribute, it should work??
Cheers,
G.

**Comment by stoiver** [comment]
This is probably associated with issue #87
